# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'team-mustard - Azure'

  # Web app name
  webAppName: 'team-mustard'

  # Environment name
  environmentName: 'team-mustard'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
            displayName: 'Install Node.js'

          - task: Npm@1
            displayName: 'npm ci'
            inputs:
              command: ci

          - task: Npm@1
            displayName: 'npm run build'
            inputs:
              command: custom
              customCommand: 'run build --if-present'

          - task: Npm@1
            displayName: 'npm run test'
            inputs:
              command: custom
              customCommand: 'run test --if-present'

          - task: DeleteFiles@1
            displayName: 'Delete unneeded files'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)'
              Contents: '.cache'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            artifact: drop

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: TeamMustard_Linux
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Azure Web App Deploy: team-mustard'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    appName: $(webAppName)
                    runtimeStack: 'NODE|12-lts'
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    startUpCommand: 'npm run start'
